### ISSUE TITLE
Bitdefender find virus in your zip as "Application.WinDivert.B"

### ISSUE THREAD

**Issue by manwithoutpant** [Include-sys/GUI-for-GoodbyeDPI#10]
![Capture](https://user-images.githubusercontent.com/39988728/110197949-1c76dc80-7e4f-11eb-9ed6-7fdbcc924596.PNG)

**Comment by Include-sys** [comment]
Hi,

It doesn't contain any malware/virus. Windivert is a networking library that allows capturing network packages in Windows Operating Systems. It's possible to evade your ISP's DPI(Deep Packet Inspection) by capturing traffic and changing it with this library. The software I made only provides a graphical user interface for the CLI(command-line) software named GoodbyeDPI which you can find it here,
https://github.com/ValdikSS/GoodbyeDPI

Since I don't actively develop this project anymore you can use original CLI software(GoodbyeDPI), DoH(DNS over HTTPS), or other tunneling&encrytion software to get freedom or privacy on the Internet. (VPN, Proxy, etc.)
